site_name: 'Tech Guides'
site_description: 'Teste.'

nav:
  - Início: 'index.md'

extra_css: [extra.css]

plugins:
  - techdocs-core
  - kroki

markdown_extensions:
  - markdown_include.include:
      base_path: docs
