site_name: 'Tech Guides'
site_description: 'Teste.'

nav:
  - Início: 'index.md'

plugins:
  - techdocs-core
  - kroki
  - pymdownx.markdown:
      markdown_extensions:
        - extra
        - def_list
        - smarty
        - toc
        - attr_list
        - meta
        - fenced_code
        - tables
        - codehilite(guess_lang=False, css_class=highlight)
