site_name: 'Tech Guides'
site_description: 'Teste.'

markdown_extensions:
  - mdx_pandoc:

nav:
  - Início: index.md
  - Princípios da Governança de APIs:
      - Aplicar os Princípios Universalmente: apis-governance-principles/apply-principles-globally.md

plugins:
  - techdocs-core
  - kroki
